GET http://localhost:3000/api/user

###
POST http://localhost:3000/api/user/
Content-Type: application/json

{
    "userName": "Akillalano",
    "fullName": "Alan",
    "email":"something@something.com",
    "password":"$SCad#2x1"
}

###
GET http://localhost:3000/api/user/60d2e19a96ad19471c563a3e


###
DELETE http://localhost:3000/api/user/60d2e16396ad19471c563a3a


###
PATCH http://localhost:3000/api/user/60d2e16396ad19471c563a3a
Content-Type: application/json

{
    "userName": "trebsu"
}
